export const enum Tools {
  ESLint = 'ESLint',
  Prettier = 'Prettier',
  StyleLint = 'StyleLint',
  Husky = 'Husky',
  LintStaged = 'Lint Staged',
  Tailwind = 'Tailwind',
  TestingLibrary = 'Testing Library',
  AddTestingLibraryExample = 'Add Testing Library Example',
  MSW = 'Mock Service Worker(msw)',
  MSWBrowser = 'Browser',
  MSWNode = 'Node',
  MSWX = 'mswx',
  Zod = 'Zod',
}
