#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

build_version=$(node bin/index.js --version)
package_version=$(node -p "require('./package.json').version")
if [ $build_version != $package_version ];
then
  echo "Version mismatch: $build_version vs $package_version"
  exit 1
fi

exit 0
